"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

export default function SignupPage() {
  const router = useRouter();
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", company: "", password: "" });
  const [error, setError] = useState("");
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (form.password.length < 6) { setError("Use a password with at least 6 characters."); return; } localStorage.setItem("supplys﻿ync-session", JSON.stringify({ email: form.email, company: form.company, signedInAt: new Date().toISOString() })); router.push("/overview"); }
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-6"><div className="w-full max-w-xl rounded-3xl border border-slate-200 bg-white p-8 shadow-soft"><div className="mb-6"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-500 font-bold text-white">S</div><h1 className="mt-5 text-3xl font-bold text-slate-900">Create your workspace</h1><p className="mt-2 text-sm text-slate-500">Set up a resilient operations environment for your team.</p></div><form onSubmit={handleSubmit} className="grid gap-4 md:grid-cols-2">{([["firstName", "First name", "Jane"], ["lastName", "Last name", "Doe"], ["email", "Work email", "you@company.com"], ["company", "Company", "North Star Manufacturing"]] as const).map(([field, label, placeholder]) => <div key={field} className={field === "email" || field === "company" ? "md:col-span-2" : ""}><label className="mb-1 block text-sm font-medium text-slate-700" htmlFor={field}>{label}</label><input id={field} required type={field === "email" ? "email" : "text"} value={form[field]} onChange={(e) => update(field, e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5" placeholder={placeholder} /></div>)}<div className="md:col-span-2"><label className="mb-1 block text-sm font-medium text-slate-700" htmlFor="password">Password</label><input id="password" required type="password" value={form.password} onChange={(e) => update("password", e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5" placeholder="At least 6 characters" /></div>{error && <p className="md:col-span-2 text-sm text-rose-600">{error}</p>}<button type="submit" className="md:col-span-2 w-full rounded-xl bg-sky-600 px-4 py-3 font-medium text-white hover:bg-sky-500">Create account</button></form><div className="mt-5 text-center text-sm text-slate-500">Already have an account? <Link href="/login" className="font-semibold text-sky-600">Log in</Link></div></div></main>;
}
